# Credits: wenxinyiyan(baidu's "chatgpt"), xmake devs
name: Build and Release  
  
on:  
  push:
        tags:
            - "v*"
  release:  
    types: [created]  
#   pull_request:
  
jobs:  
  build_and_release:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4.1.1
  
      - name: Setup xmake  
        uses: xmake-io/github-action-setup-xmake@v1  
        with:  
          xmake-version: latest  
  
      - name: Setup APE loader
        run: |
          sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
          sudo chmod +x /usr/bin/ape
          sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
          sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

      - name: Build with xmake  
        run: xmake -y
  
      - name: Move the binary  
        run: xmake install -o build/binary

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: screenfetch-c_artifact
            path: build/build/binary
      - name: Upload Build Artifacts to GitHub Release  
        uses: svenstaro/upload-release-action@v2.9.0  
        with:  
          repo_token: ${{ secrets.GITHUB_TOKEN }}  
          file: build/binary/screenfetch-c.com
          asset_name:  screenfetch-c.com
          tag: ${{ github.ref }}  
          overwrite: true